FROM php:7-fpm

MAINTAINER Mike Stevens <mistevs@gmail.com>

#from https://github.com/docker-library/php/issues/132
#plus some custom stuff
## memcached, curl, pdo, opcache, handful of utility libraries
RUN apt-get update \
        && buildDeps=" \
                git \
                libmemcached-dev \
                zlib1g-dev \
                libmcrypt-dev \
                libcurl4-openssl-dev \
        " \
        && doNotUninstall=" \
                libmcrypt4 \
                libmemcached11 \
                libmemcachedutil2 \
        " \
        && apt-get install -y $buildDeps --no-install-recommends \
        && rm -r /var/lib/apt/lists/* \
        \
        && docker-php-source extract \
        && git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached/ \
        && docker-php-ext-install memcached curl mbstring mcrypt opcache bcmath iconv \
        \
        && docker-php-source delete \
        && apt-mark manual $doNotUninstall \
        && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $buildDeps